name = "ai-feidom-docs-agent"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 构建配置
[build]
command = "npm run build"

# 环境变量配置
[vars]
NODE_ENV = "production"

# 如果需要环境变量
# [vars]
# OPENAI_API_KEY = "your-openai-api-key"

# 如果需要 KV 存储
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"
# preview_id = "your-preview-kv-id"

# 如果需要 D1 数据库
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id" 